#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/bingwallpaper ]; then
  rm -f /usr/doc/bingwallpaper
fi
# End automatically added section